# ===============================
# CONEXIÓN A LA BASE DE DATOS (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/queboleta_db
spring.datasource.username=postgres
spring.datasource.password=0207
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE (JPA)
# ===============================
# update: Crea o actualiza las tablas automáticamente basándose en tus clases de Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto donde correrá el servidor Backend
server.port=8080